[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
oft = "FXnms2y5FUjzxzEaDEnEF54pYWZLteTdKUwQhDbCAUfL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./junk-id.json"

[scripts]
test = "npx jest test/anchor"
